<a href="https://colab.research.google.com/github/salwa-ayudia/pm-turi2-preprocessing-SalwaAyudiaPutri/blob/main/PM_P4_SalwaAyudiaPutri_2488010042.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [147]:
import pandas as pd
import numpy as np

data = {
    'usia': [19, 22, np.nan, 45, 17, 42, 20, np.nan, 18, 30],
    'pendapatan': [5_000_000, 8_300_000, 7_500_000, 20_000_000, 5_700_000, 19_000_000, 9_100_000, 3_300_000, np.nan, 10_900_000],
    'pendidikan': ['SMA', 'S1', 'SMA', 'S2', 'SMA', 'S2', 'S1', 'S1', 'SMA', 'S2'],
    'kota': ['Bandung', 'Cirebon', 'Bandung', 'Indramayu', 'Cirebon', 'Indramayu', 'Cirebon', 'Bandung', 'Bandung', 'Cirebon'],
    'membeli': ['Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Tidak', 'Ya'],
}

df = pd.DataFrame(data)
df

   usia  pendapatan pendidikan       kota membeli
0  19.0   5000000.0        SMA    Bandung   Tidak
1  22.0   8300000.0         S1    Cirebon      Ya
2   NaN   7500000.0        SMA    Bandung   Tidak
3  45.0  20000000.0         S2  Indramayu      Ya
4  17.0   5700000.0        SMA    Cirebon   Tidak
5  42.0  19000000.0         S2  Indramayu      Ya
6  20.0   9100000.0         S1    Cirebon      Ya
7   NaN   3300000.0         S1    Bandung   Tidak
8  18.0         NaN        SMA    Bandung   Tidak
9  30.0  10900000.0         S2    Cirebon      Ya

In [148]:
df_median = df.copy()

# Latihan Mandiri

1. Ganti imputasi usia menjadi mean; bandingkan hasilnya.

In [149]:
df_median['usia'] = df_median['usia'].fillna(df_median['usia'].median())
df_median['pendapatan'] = df_median['pendapatan'].fillna(df_median['pendapatan'].median())

print("Mean usia:", df_median['usia'].median())
print("Mean pendapatan:", df_median['pendapatan'].median())
print(display(df_median))

Mean usia: 21.0
Mean pendapatan: 8300000.0

   usia  pendapatan pendidikan       kota membeli
0  19.0   5000000.0        SMA    Bandung   Tidak
1  22.0   8300000.0         S1    Cirebon      Ya
2  21.0   7500000.0        SMA    Bandung   Tidak
3  45.0  20000000.0         S2  Indramayu      Ya
4  17.0   5700000.0        SMA    Cirebon   Tidak
5  42.0  19000000.0         S2  Indramayu      Ya
6  20.0   9100000.0         S1    Cirebon      Ya
7  21.0   3300000.0         S1    Bandung   Tidak
8  18.0   8300000.0        SMA    Bandung   Tidak
9  30.0  10900000.0         S2    Cirebon      Ya

None

In [150]:
df['usia'] = df['usia'].fillna(df['usia'].mean())
df['pendapatan'] = df['pendapatan'].fillna(df['pendapatan'].mean())

print("Mean usia:", df['usia'].mean())
print("Mean pendapatan:", df['pendapatan'].mean())
print(display(df))

Mean usia: 26.625
Mean pendapatan: 9866666.666666668

     usia    pendapatan pendidikan       kota membeli
0  19.000  5.000000e+06        SMA    Bandung   Tidak
1  22.000  8.300000e+06         S1    Cirebon      Ya
2  26.625  7.500000e+06        SMA    Bandung   Tidak
3  45.000  2.000000e+07         S2  Indramayu      Ya
4  17.000  5.700000e+06        SMA    Cirebon   Tidak
5  42.000  1.900000e+07         S2  Indramayu      Ya
6  20.000  9.100000e+06         S1    Cirebon      Ya
7  26.625  3.300000e+06         S1    Bandung   Tidak
8  18.000  9.866667e+06        SMA    Bandung   Tidak
9  30.000  1.090000e+07         S2    Cirebon      Ya

None

#### Perbandingan Hasil:
Pada imputasi median semua nilai kosong (NaN) baik di kolom usia maupun pendapatan digantikan dengan nilai tengah, sedangkan pada imputasi mean semua nilai kosong nya digantikan oleh nilai rata-rata. Sehingga nilai pengganti untuk NaN berbeda antara median dan mean.

3. Tambahkan kolom kategorikal baru dan terapkan one-hot encoding.

In [151]:
X = df.drop(columns=['membeli'])
y = df['membeli']

X['pendidikan'] = X['pendidikan'].map({'SMA':0,'S1':1,'S2':2})
X = pd.get_dummies(X, columns=['kota'], dtype=int)
y = y.map({'Tidak':0,'Ya':1})

print("Hasil encoding X:")
display(X)

print("\n\nHasil encoding y:")
display(y)

Hasil encoding X:

,usia,pendapatan,pendidikan,kota_Bandung,kota_Cirebon,kota_Indramayu
0,19.000,5.000000e+06,0,1,0,0
1,22.000,8.300000e+06,1,0,1,0
2,26.625,7.500000e+06,0,1,0,0
3,45.000,2.000000e+07,2,0,0,1
4,17.000,5.700000e+06,0,0,1,0
5,42.000,1.900000e+07,2,0,0,1
6,20.000,9.100000e+06,1,0,1,0
7,26.625,3.300000e+06,1,1,0,0
8,18.000,9.866667e+06,0,1,0,0
9,30.000,1.090000e+07,2,0,1,0

Hasil encoding y:

0    0
1    1
2    0
3    1
4    0
5    1
6    1
7    0
8    0
9    1
Name: membeli, dtype: int64

2. Gunakan MinMaxScaler (0–1) sebagai ganti StandardScaler; tampilkan describe().

In [152]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(
X, y, test_size=0.3, random_state=42)


from sklearn.preprocessing import MinMaxScaler
num = ['usia','pendapatan','pendidikan']
sc = MinMaxScaler()

X_train[num] = sc.fit_transform(X_train[num])
X_test[num] = sc.transform(X_test[num])

print("Hasil X_train setelah MinMaxScaler:")
display(X_train)

print("\n\nHasil X_test setelah MinMaxScaler:")
display(X_test)

print("\n\nDescribe X_train:")
display(X_train[num].describe())

Hasil X_train setelah MinMaxScaler:

,usia,pendapatan,pendidikan,kota_Bandung,kota_Cirebon,kota_Indramayu
0,0.071429,0.101796,0.0,1,0,0
7,0.343750,0.000000,0.5,1,0,0
2,0.343750,0.251497,0.0,1,0,0
9,0.464286,0.455090,1.0,0,1,0
4,0.000000,0.143713,0.0,0,1,0
3,1.000000,1.000000,1.0,0,0,1
6,0.107143,0.347305,0.5,0,1,0

Hasil X_test setelah MinMaxScaler:

,usia,pendapatan,pendidikan,kota_Bandung,kota_Cirebon,kota_Indramayu
8,0.035714,0.393214,0.0,1,0,0
1,0.178571,0.299401,0.5,0,1,0
5,0.892857,0.940120,1.0,0,0,1

Describe X_train:

           usia  pendapatan  pendidikan
count  7.000000    7.000000    7.000000
mean   0.332908    0.328486    0.428571
std    0.339773    0.333335    0.449868
min    0.000000    0.000000    0.000000
25%    0.089286    0.122754    0.000000
50%    0.343750    0.251497    0.500000
75%    0.404018    0.401198    0.750000
max    1.000000    1.000000    1.000000

4. Jelaskan mengapa fit_transform pada latih tetapi hanya transform pada uji.


*  Jawab: <br>
Karena fit_transform digunakan untuk mempelajari kategori yang unik dan mengubah nya menjadi kolom biner (0 dan 1) agar komputer dapat memprosesnya, sedangkan data uji hanya menggunakan transform saja. Ini bertujuan untuk menjaga konsistensi jumlah dan urutan kolom agar model nya tidak error dan mencegah terjadinya kebocoran data (data leakage).

# Refleksi

1. Mengapa urutan 'split dulu, baru scaling' penting?


*   Jawab: <br>
Karena jika penskalaan (scaling) di fit pada seluruh data sebelum di split, informasi data uji nya akan bocor ke pelatihan. Akibatnya evaluasi menjadi tidak jujur dan model tampak lebih baik daripada kenyataanya.

2. Kapan label encoding dan kapan one-hot encoding?


*   Jawab: <br>
Label encoding cocok digunakan saat data nya adalah data ordinal (berurutan), karena mengubah teks menjadi angka berurutan yang hasilnya adalah satu kolom angka. <br>
One-hot encoding cocok digunakan untuk data nominal (tanpa urutan) dengan cara membuat kolom biner baru (0 dan 1) sehingga kolom akan membengkak.

3. Apa perbedaan normalisasi dan standardisasi?


*   Jawab: <br>
Normalisasi (Min-Max) berguna bila butuh batas yang jelas, skala ke rentang tetap 0-1, dan sensitif terhadap outlier. Sedangkan Standardisasi (Z-core) tidak membatasi rentang, lebih tahan outlier serta mengubah mean (rata-rata) = 0 dan standar deviasi = 1.